# Generated by Django 3.1.2 on 2020-11-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='breed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
