# Generated by Django 3.1.2 on 2021-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20201115_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='picture',
            field=models.ImageField(editable=False, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='animal',
            field=models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato')], max_length=16),
        ),
    ]
