# Generated by Django 3.1.2 on 2021-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20210221_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
