# Generated by Django 3.1.7 on 2021-03-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20210317_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaprod',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='update',
            new_name='updated',
        ),
    ]
